language: perl

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
  - cpanm --notest --skip-satisfied Dist::Zilla Moose::Autobox
  - dzil authordeps --missing | cpanm --notest --skip-satisfied
  - dzil listdeps --missing | cpanm --notest --skip-satisfied

script:
  - dzil smoke --release
